branches:
  only:
    - master

language: perl6

perl6:
  - latest

install:
  - rakudobrew build-zef
  - zef --/test --depsonly install .

#cache:
#  directories:
#    - $TRAVIS_BUILD_DIR/.rakudobrew
